---
version: "3.9"
  
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "29000:9000"   # S3-API
      - "29001:9001"   # Web-UI
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    volumes:
      - data:/data

volumes: 
  data:
