---
services:
  siteb_runner:
    container_name: gitflic-runner-siteb
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
    image: registry.gitflic.ru/project/maks1ms/gitflic-runner/gitflic-runner:3.4.1
    volumes:
      - /volume1/docker/apps/gitflic-runner/config/siteb:/root/gitflic-runner/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REG_URL: https://coordinator.gitflic.ru/-/runner/registration
      REG_TOKEN: ${SITEB_TOKEN}
      EXECUTOR: docker
      DIDENABLE: true
      LOG_NAME: server.log

volumes:
  gitflic_runner_siteb:
