---
version: '3.9'

services:
  3x-ui:
    # https://github.com/MHSanaei/3x-ui/wiki/Installation
    image: bigbugcc/3x-ui:v2.8.10
    container_name: 3x-ui
    restart: unless-stopped
    # admin:admin by defaul
    # https://github.com/MHSanaei/3x-ui/wiki/Configuration
    environment:
      TZ: "Etc/UTC"
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_DB_FOLDER: "/etc/x-ui"
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - db:/etc/x-ui
      - cert:/root/cert
    ports:
      - "2053:2053"      # Web UI HTTPS
      - "2096:2096"      # Web UI HTTP
      - "443:443"        # Xray VMess/VLESS/Trojan
      - "80:80"          # HTTP fallback/Xray
    # Additional inbound ports (add as needed)
    # - "1080:1080"      # SOCKS proxy
    # - "8080:8080"      # HTTP proxy
    # config in /app/bin/config.json
volumes:
  db:
  cert:

# client from https://v2raytun.com
# change account pass, default admin/admin
# xray -> basic -> ensure bittorent blocked
# xray -> outgoing -> add warp+create connection -> set warp endpoint to result of `nslookup engage.cloudflareclient.com` -> # xray -> routing -> add network tcp,udp; outbound tag warp
# xray -> routing -> add -> domain: ext:geosite_(IR/CN/RU).dat:(ir/cn/ru)-available-only-inside,regexp:.*\.ir$; outbound tag: blocked
# add connection -> proto vless;port 443; security Reality; flow xtls-rprx-vision; target&sni rotate or set own; transport tcp(raw); uTLS not android -> Get New Cert + Sniffing
