---
version: "3.9"

services:
  ingress:
    image: traefik:3.5
    command:
      # Tells Traefik to listen to docker
      - --providers.docker.network=ingress
      # Enables the web UI
      - --api.insecure=${IS_WEB_UI_ENABLED}
      - --log.level=${LOG_LEVEL}
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/acme/acme.json
      # Default: "https://acme-v02.api.letsencrypt.org/directory"
      - --certificatesResolvers.letsencrypt.acme.caserver=${ACME_CASERVER}
      - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true
      - --accesslog=true
#      - --tracing=true
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    labels:
      - "traefik.enable=false"
    networks:
      - ingress
    environment:
      # https://doc.traefik.io/traefik/reference/static-configuration/env/
      - IS_WEB_UI_ENABLED
      - LOG_LEVEL
      - ACME_EMAIL
      - ACME_CASERVER
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/acme

networks:
  ingress:
    name: "ingress"

volumes:
  acme:
