server {
    listen       80 default_server;
    server_name  _;

    charset utf-8;
    access_log /dev/stdout;
    error_log /dev/stderr debug;
    root   /usr/share/nginx/html;
    error_page   500 502 503 504  /50x.html;

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
        try_files $uri =404;
    }

    location / {
        add_header X-Config "my-server-block" always;
        try_files $uri $uri/ =404;
    }
}
