---
version: "3.9"

services:
  ingress:
    image: traefik:v2.2
    command:
      # Tells Traefik to listen to config file
      - --providers.file.filename=/etc/traefik/services.yml
      # Enables the web UI
      - --api.insecure=${IS_WEB_UI_ENABLED}
      - --log.level=${LOG_LEVEL}
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.caserver=${ACME_CASERVER}
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - ingress
    environment:
      # https://doc.traefik.io/traefik/reference/static-configuration/env/
      - IS_WEB_UI_ENABLED
      - LOG_LEVEL
      - ACME_EMAIL
      - ACME_CASERVER
    configs:
      - source: services
        target: /etc/traefik/services.yml
  index:
    build: index/.
    pull_policy: build
    networks:
      - ingress
    environment:
      - INDEX_HOSTNAME

configs:
  services:
    # https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
    content: |
      http:
        routers:
          index:
            rule: "Host(`${INDEX_HOSTNAME}`) && Path(`/`)"
            service: index
            tls.certresolver: letsencrypt
        services:
          index:
            loadBalancer:
              servers:
                - url: "http://index"

networks:
  ingress:
