---
# https://github.com/jlesage/docker-handbrake
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake:v24.03.1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 200M
        limits:
          memory: 2048M
    ports:
      - 5800:5800
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - handbrake_app:/config
      - media_video:/storage
    environment:
      - TZ=Europe/Moscow
      - USER_ID=${UID}
      - GROUP_ID=${GID}
      - AUTOMATED_CONVERSION=0

volumes:
  handbrake_app:
  media_video:
    external: true
