---
services:
  portainer:
    image: portainer/portainer-ce:2.27.1-alpine
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    command: --admin-password '${ADMIN_PASS}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_app:/data
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 1G

volumes:
  portainer_app:
