---
version: '3.9'

services:
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888  # file api
      - 18888:18888  # grpc
      - 9326:9326  # metrics
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    volumes:
      - filer:/data
    stdin_open: true
    networks:
      - seaweed
      - storage-apis
#  s3:
#    image: chrislusf/seaweedfs
#    ports:
#      - 8333:8333 # s3 api
#      - 9327:9327 # metrics
#    command:
#      - 's3'
#      - '-filer="filer:8888"'
#      - '-ip.bind=0.0.0.0'
#      - '-metricsPort=9327'
#      - '-port=8333'
#      -'-config=/config/s3.json'
#    depends_on:
#      - filer
#    volumes:
#      - ./s3/config.json:/config/s3.json
#    networks:
#      - storage-apis
#  webdav:
#    image: chrislusf/seaweedfs # use a remote image
#    ports:
#      - 7333:7333
#    command: 'webdav -filer="filer:8888"'
#    depends_on:
#      - master
#      - volume
#      - filer

volumes:
  filer:

networks:
  seaweed:
    external: true
  storage-apis:
