name: scheduled
on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  schedule:
    - cron: "15 */4 * * *"
jobs:
  update-utils:
    name: Test restoring vaultwarden database
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: restore
        run: make test-restore
